#!/usr/bin/env bash
#Ascript that displays this;
#Show 4 and then bad luck from Chine for the 4th loop iteration
#Show 9 and then bad luck from Japan for the 9th loop iteration
#Show 17 and then bad luck from Italy for the 17th  loop iteration
j=1
while [ $j -le 20 ]
do
	echo $j
	case $j in
		4) echo "bad luck from China"
			;;
		9) echo "bad luck from Japan"
			;;
		17) echo "bad luck from Italy"
			;;
	esac
	j=$((j+1))
done
